// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package db

import (
	"database/sql"
	"time"

	uuid "github.com/gofrs/uuid/v5"
)

type User struct {
	ID        uuid.UUID
	Username  string
	Email     string
	Password  string
	AvatarUrl sql.NullString
	CreatedAt time.Time
	DeletedAt time.Time
}
